# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:

* main

pool:
name: 'Default'

stages:

* stage: Build
  jobs:

  * job: BuildJob
    steps:

    * task: DotNetCoreCLI@2
      inputs:
      command: 'restore'
      projects: '**/*.csproj'

    * task: DotNetCoreCLI@2
      inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

    * task: DotNetCoreCLI@2
      inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    * task: PublishBuildArtifacts@1
      inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'WeatherAPI'

* stage: Deploy_QA
  dependsOn: Build

  jobs:

  * deployment: DeployQA
    environment: QA

    strategy:
    runOnce:
    deploy:
    steps:

    ```
      - download: current
        artifact: WeatherAPI

      - powershell: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "WeatherAPI"

      - powershell: |
          Copy-Item "$(Pipeline.Workspace)\WeatherAPI\*" "C:\inetpub\wwwroot\WeatherAPI" -Recurse -Force

      - powershell: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "WeatherAPI"
    ```

* stage: Deploy_PROD
  dependsOn: Deploy_QA

  jobs:

  * deployment: DeployProd
    environment: PROD

    strategy:
    runOnce:
    deploy:
    steps:

    ```
      - download: current
        artifact: WeatherAPI

      - powershell: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "Prod.WeatherAPI"

      - powershell: |
          Copy-Item "$(Pipeline.Workspace)\WeatherAPI\*" "C:\inetpub\wwwroot\WeatherAPI_PROD" -Recurse -Force

      - powershell: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "Prod.WeatherAPI"
    ```
