# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - main

# pool:
#   name: 'Default'

# stages: 

# steps:

# - task: UseDotNet@2
#   displayName: 'Install .NET SDK'
#   inputs:
#     packageType: 'sdk'
#     version: '8.0.404'

# - task: DotNetCoreCLI@2
#   displayName: 'Restore'
#   inputs:
#     command: 'restore'
#     projects: '**/*.csproj'

# - task: DotNetCoreCLI@2
#   displayName: 'Build'
#   inputs:
#     command: 'build'
#     projects: '**/*.csproj'
#     arguments: '--configuration Release'

# - task: DotNetCoreCLI@2
#   displayName: 'Test'
#   inputs:
#     command: 'test'
#     projects: '**/*Tests.csproj'
#     arguments: '--configuration Release'

# - task: DotNetCoreCLI@2
#   displayName: 'Publish'
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact'
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: 'WeatherAPI'

# # - powershell: |
# #     Import-Module WebAdministration
# #     Stop-WebAppPool -Name "WeatherAPI"
# #   displayName: 'Stop App Pool'

# # - powershell: |
# #     dotnet publish "$(Build.SourcesDirectory)\GetWeatherAPI.csproj" `
# #       -c Release `
# #       -o "C:\inetpub\wwwroot\WeatherAPI"
# #   displayName: 'Publish To IIS'

# # - powershell: |
# #     Import-Module WebAdministration
# #     Start-WebAppPool -Name "WeatherAPI"
# #   displayName: 'Start App Pool'
trigger:
- main

pool:
  name: 'Default'

stages:

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: 'Build and Publish Artifact'

  jobs:
  - job: BuildJob
    displayName: 'Build'

    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.404'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'WeatherAPI'


# =========================
# DEPLOY QA
# =========================
- stage: Deploy_QA
  displayName: 'Deploy To QA'
  dependsOn: Build

  jobs:
  - deployment: DeployQA
    displayName: 'Deploy QA'
    environment: 'QA'

    strategy:
      runOnce:
        deploy:

          steps:

          - download: current
            artifact: WeatherAPI

          - powershell: |
               Get-ChildItem "$(Pipeline.Workspace)\WeatherAPI" -Recurse
            displayName: 'Show Downloaded Files'

          - powershell: |
              Import-Module WebAdministration
              Stop-WebAppPool -Name "WeatherAPI"
            displayName: 'Stop QA App Pool'

          - powershell: |
              Remove-Item "C:\inetpub\wwwroot\WeatherAPI\*" -Recurse -Force -ErrorAction SilentlyContinue
              Expand-Archive `
                -Path "$(Pipeline.Workspace)\WeatherAPI\s.zip" `
                -DestinationPath "C:\inetpub\wwwroot\WeatherAPI" `
                -Force
            displayName: 'Extract Files To QA'

          - powershell: |
              Import-Module WebAdministration
              Start-WebAppPool -Name "WeatherAPI"
            displayName: 'Start QA App Pool'


# =========================
# DEPLOY PROD
# =========================
- stage: Deploy_PROD
  displayName: 'Deploy To PROD'
  dependsOn: Deploy_QA

  jobs:
  - deployment: DeployPROD
    displayName: 'Deploy PROD'
    environment: 'PROD'

    strategy:
      runOnce:
        deploy:

          steps:

          - download: current
            artifact: WeatherAPI

          - powershell: |
               Get-ChildItem "$(Pipeline.Workspace)\WeatherAPI" -Recurse
            displayName: 'Show Downloaded Files'

          - powershell: |
              Import-Module WebAdministration
              Stop-WebAppPool -Name "Prod.WeatherAPI"
            displayName: 'Stop PROD App Pool'

          - powershell: |
              Copy-Item "$(Pipeline.Workspace)\WeatherAPI\*" `
                "C:\inetpub\wwwroot\WeatherAPI_PROD" `
                -Recurse -Force
            displayName: 'Copy Files To PROD'

          - powershell: |
              Import-Module WebAdministration
              Start-WebAppPool -Name "Prod.WeatherAPI"
            displayName: 'Start PROD App Pool'